# Generated by Django 2.2.3 on 2020-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='mode',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='light',
            name='status',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
