# Generated by Django 2.2.3 on 2020-11-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0004_auto_20201115_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='areafk',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='light.area'),
        ),
    ]
